import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

def job_applicant_custom_fields():
    custom_fields = {'Job Applicant': [{
   'label': 'Experience Type',
   'fieldname': 'experience_type',
   'insert_after': 'status',
   'length': 0,
   'fieldtype': 'Select',
   'options': '\nFresher\nExperience',
   'fetch_from': None,
   'default': None,
   'depends_on': '',
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Experience Detail',
   'fieldname': 'experience_detail',
   'insert_after': 'details_section',
   'length': 0,
   'fieldtype': 'Link',
   'options': 'Job Application Experience Details',
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 1},
  {'label': 'Experience Details',
   'fieldname': 'experience_details',
   'insert_after': 'experience_type',
   'length': 0,
   'fieldtype': 'Table',
   'options': 'Job Application Experience Details',
   'fetch_from': None,
   'default': None,
   'depends_on': 'eval:doc.experience_type=="Experience"',
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Employee Educations',
   'fieldname': 'employee_educations',
   'insert_after': 'experience_detail',
   'length': 0,
   'fieldtype': 'Link',
   'options': 'Employee Education',
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 1},
  {'label': 'Employee Education',
   'fieldname': 'employee_education',
   'insert_after': 'country',
   'length': 0,
   'fieldtype': 'Table',
   'options': 'Employee Education',
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Workflow State',
   'fieldname': 'workflow_state',
   'insert_after': None,
   'length': 0,
   'fieldtype': 'Link',
   'options': 'Workflow State',
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 1},
  {'label': 'Position Applied',
   'fieldname': 'ts_position_applied',
   'insert_after': 'designation',
   'length': 0,
   'fieldtype': 'Link',
   'options': 'Job Opening',
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'DOB',
   'fieldname': 'ts_dob',
   'insert_after': 'phone_number',
   'length': 0,
   'fieldtype': 'Date',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 1,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Job Type',
   'fieldname': 'ts_job_type',
   'insert_after': 'ts_dob',
   'length': 0,
   'fieldtype': 'Select',
   'options': '\nPart-Time\nFull Time\nWork From Home',
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 1,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Address Information',
   'fieldname': 'section_break_18',
   'insert_after': 'experience_details',
   'length': 0,
   'fieldtype': 'Section Break',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Address',
   'fieldname': 'ts_address',
   'insert_after': 'section_break_18',
   'length': 0,
   'fieldtype': 'Small Text',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 1,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Education Details',
   'fieldname': 'ts_education_details',
   'insert_after': 'section_edu',
   'length': 0,
   'fieldtype': 'Table',
   'options': 'Job Application Education Details',
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 1,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Currently Pursuing',
   'fieldname': 'currently_pursuing',
   'insert_after': 'section',
   'length': 0,
   'fieldtype': 'Check',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': '',
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': '',
   'fieldname': 'section',
   'insert_after': 'ts_education_details',
   'length': 0,
   'fieldtype': 'Section Break',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': '',
   'fieldname': 'section_edu',
   'insert_after': 'experience_type',
   'length': 0,
   'fieldtype': 'Section Break',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Personal details',
   'fieldname': 'personal_details',
   'insert_after': 'ts_address',
   'length': 0,
   'fieldtype': 'Section Break',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Parent/Guardian Name',
   'fieldname': 'parentguardian_name',
   'insert_after': 'personal_details',
   'length': 0,
   'fieldtype': 'Data',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Mobile Number',
   'fieldname': 'mobile_number',
   'insert_after': 'parentguardian_name',
   'length': 0,
   'fieldtype': 'Data',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': None,
   'fieldname': 'column_break_27',
   'insert_after': 'mobile_number',
   'length': 0,
   'fieldtype': 'Column Break',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Parent/Guardian Occupation',
   'fieldname': 'parentguardian_occupation',
   'insert_after': 'column_break_27',
   'length': 0,
   'fieldtype': 'Data',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'How they are related to you ?',
   'fieldname': 'how_they_are_related_to_you_',
   'insert_after': 'parentguardian_occupation',
   'length': 0,
   'fieldtype': 'Data',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Referral Employee Name',
   'fieldname': 'referral_employee_name',
   'insert_after': 'column_break_13',
   'length': 0,
   'fieldtype': 'Data',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Attachments',
   'fieldname': 'attachments',
   'insert_after': 'applicant_rating',
   'length': 0,
   'fieldtype': 'Section Break',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Government ID Proof Attachment',
   'fieldname': 'government_id_proof_attachment',
   'insert_after': 'attachments',
   'length': 0,
   'fieldtype': 'Attach',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 1,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Linkedin Profile',
   'fieldname': 'linkedin_profile',
   'insert_after': 'government_id_proof_attachment',
   'length': 0,
   'fieldtype': 'Data',
   'options': None,
   'fetch_from': None,
   'default': 'URL',
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Photo Attachment',
   'fieldname': 'photo_attachment',
   'insert_after': 'column_break_39',
   'length': 0,
   'fieldtype': 'Attach',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': None,
   'fieldname': 'column_break_39',
   'insert_after': 'linkedin_profile',
   'length': 0,
   'fieldtype': 'Column Break',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0},
  {'label': 'Salary Expectation',
   'fieldname': 'salary_expectation',
   'insert_after': 'currency',
   'length': 0,
   'fieldtype': 'Data',
   'options': None,
   'fetch_from': None,
   'default': None,
   'depends_on': None,
   'mandatory_depends_on': None,
   'read_only_depends_on': None,
   'reqd': 0,
   'read_only': 0,
   'hidden': 0}]}

    create_custom_fields(custom_fields)

